#!/usr/bin/perl
# Small wrapper for pdftk
# to quickly split pdf
use strict;
use warnings;

# Exclude Backups and .cache directories
#
# Need to escape backslashes in "\(" and "\)"
# The usual shell command doesn't require escaping these
chomp(my $input_pdf = `find . \\( -path "*/Backups" -o -path "*/\.cache" \\) -prune -o -iname "*.pdf" -print | fzf`);

print "Enter in the page(s) that you want output (See 3 examples below):\n";
print "\t1\n";
print "\t1 3 5\n";
print "\t2-3\n";
print "\n";
chomp(my $pages = <STDIN>);

print "Enter in the name of the output pdf (don't include the .pdf at the end)\n";
chomp(my $output_name = <STDIN>);

`pdftk "$input_pdf" cat $pages output "$output_name.pdf"` or print_error_message();

print "FINISHED. Saved to \"$output_name.pdf\"\n";

sub print_error_message {
  print "\n";
  print "====== Make sure you entered in the required information properly! =====\n";
  die "ERROR: issue creating the output pdf";
}
