#!/usr/bin/perl
# Searxng up
# Pull down latest searxng image and start it up
# If an instance is already running, this will stop it and start a new one
use strict;
use warnings;

my $searxng_dir = "$ENV{'HOME'}/.otherPrograms/searxng-docker";
my $port = 8888;

my $container_name = get_container_name();

# Don't attempt to stop container if searx image isn't already running
if ($container_name) {
  system("docker stop $container_name");
}
chdir($searxng_dir) or die "Error: can't cd into $searxng_dir";
system("docker pull searxng/searxng");
exec("docker run --rm -d -v $searxng_dir/searxng:/etc/searxng -p $port:8080 -e BASE_URL=http://localhost:$port/ searxng/searxng");

sub get_container_name {
  my @docker_ps_output = `docker ps`;

  foreach my $line (@docker_ps_output) {
    # Check for the line that uses the 'searxng/searxng' image and extract the
    # container name
    if ($line =~ /searxng\/searxng/ && $line =~ /(?<container_name>[a-z]+_[a-z]+\Z)/) {
      return $+{container_name};
    }
  }
}
